import './globals.css'
import { Montserrat } from 'next/font/google'

export const metadata = {
  title: 'Blog App',
  description: 'Generated by create next app',
}

const monserrat = Montserrat({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-monserrat',
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${monserrat.className}`}>
        <div className="flex min-h-screen flex-col items-center justify-between p-24">
          {children}
        </div>
      </body>
    </html>
  )
}
