import "./globals.css";
import { Montserrat } from "next/font/google";

export const metadata = {
  title: "Blog App",
  description: "Generated by create next app",
};

const monserrat = Montserrat({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-monserrat",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={monserrat.className}>
        <h1 className="text-2xl pt-12 uppercase text-center">
          Blog app nextjs
        </h1>
        {children}
      </body>
    </html>
  );
}
